// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpFXzRWss-h108IpAmf34i8uo8FL_Mf3U',
    appId: '1:1012959371446:web:a978a21e281cd4b3634617',
    messagingSenderId: '1012959371446',
    projectId: 'ucompensar-app',
    authDomain: 'ucompensar-app.firebaseapp.com',
    storageBucket: 'ucompensar-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqF1ZSTpg9qOtO7oipNxRJRLLE3mqG0pQ',
    appId: '1:1012959371446:android:7b901ce1672231fb634617',
    messagingSenderId: '1012959371446',
    projectId: 'ucompensar-app',
    storageBucket: 'ucompensar-app.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg0P82g-5BX-DomOsISvAJcWA5bbdzbpY',
    appId: '1:1012959371446:ios:5e008f839d59f38b634617',
    messagingSenderId: '1012959371446',
    projectId: 'ucompensar-app',
    storageBucket: 'ucompensar-app.appspot.com',
    iosBundleId: 'com.example.residentsApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg0P82g-5BX-DomOsISvAJcWA5bbdzbpY',
    appId: '1:1012959371446:ios:5e008f839d59f38b634617',
    messagingSenderId: '1012959371446',
    projectId: 'ucompensar-app',
    storageBucket: 'ucompensar-app.appspot.com',
    iosBundleId: 'com.example.residentsApp',
  );

}